### ISSUE TITLE
Flaky image loading when using css content

### ISSUE THREAD

**Issue by StephenLarkin** [simonhaenisch/md-to-pdf#27]
I have a series of documents that we're using for our markdown documentation. Each of them has a title page with a header and footer, which I'm injecting in using the css content property to avoid duplication.

The header contains an image of our company logo, but I've been finding that when I compile the file, sometimes it doesn't load in, leaving just a blank space at the top.

```css
&::before {
  content: url("img/logo.svg");
  display: block;
  height: 80px;
}
```

I can only assume that, as it works perfectly fine around half of the time, that there is some sort of race condition between loading the page in chromium headless and printing out to the pdf.
