### ISSUE TITLE
CSS content urls are evaluated relative to the markdown file instead of the CSS file

### ISSUE THREAD

**Issue by TabithaLarkin** [simonhaenisch/md-to-pdf#28]
One thing that I have noticed though is that there seems to be some inconsistency with the evaluation of the content url in the CSS file. If the below structure is used then these are the outcomes:

- file.md
- img/logo.svg
- style/style.css
- subFolder/otherFile.md

`style/style.css` includes:

```css
.class::before {
  content: url("img/logo.svg");
}
```

This will evaluate fine for `file.md` but fail for `otherFile.md`. It seems that the content url is being evaluated relative to the `.md` file and not the `.css` file as it should be.

The css should be:

```css
.class::before {
  content: url("../img/logo.svg");
}
```

This is because the content include should be relative to the location of the `style.css` file, meaning that the css could be applied to any file in any sub directory consistently.
