### ISSUE TITLE
How to set a repeating background without margins

### ISSUE THREAD

**Issue by kgrubb** [simonhaenisch/md-to-pdf#42]
**Problem:**

Hey, I apologize if this is a dumb question, but I just can't seem to figure out how to create a repeating background on the pdfs generated using md-to-pdf. I'm wanting to create a parchment effect, instead of a white background on my pdf output. I've been playing around with something like this in my css for testing:

```css
* {
  background: url(http://api.thumbr.it/whitenoise-361x370.png?background=ffffffff&noise=5c5c5c&density=13&opacity=62);
  background-repeat: repeat;
  background-position: center center;
}
```

I also have `printBackground: true` in my pdf options. The background will show up behind everything except the margin-ed areas:

<img width="548" alt="Screen Shot 2019-08-16 at 4 06 59 PM" src="https://user-images.githubusercontent.com/8471701/63195167-e8a34e80-c03f-11e9-843a-8affc17a3bf4.png">

Any tips/ideas on how to get the background to cover all whitespace on the page?

**Comment by simonhaenisch** [comment]
After trying a few things, from what I can tell the only option you have is to remove the margin from the page. Sadly you can't set `padding` using the [`@page` rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@page) 😕 That means you'll have to set the padding on your `body`:

```yml
pdf_options:
  printBackground: true
  format: A4
  margin: 0mm
css: >-
  body {
    padding: 30mm 25mm;
    background: url(http://api.thumbr.it/whitenoise-361x370.png?background=ffffffff&noise=5c5c5c&density=13&opacity=62);
    background-repeat: repeat;
    background-position: center center;
  }
```

However, then you'll have to deal with the fact that the padding is only at the top of the first page and the bottom of the last page (could potentially work around it with manual page breaks and padding with elements). BUT: for some reason the background only renders on the first page for me 🤷🏻‍♂️

![image](https://user-images.githubusercontent.com/3410759/63202107-7c990880-c088-11e9-972a-0e8959efffed.png)

So, if this is for a one-page document, no margin and padding instead could help you, otherwise I'm afraid this is probably something that's not yet solvable with Puppeteer. You can try to study https://www.w3.org/TR/css-page-3/#page-model though, maybe you can find sth in there.
